config/routes.rb
Rails.application.routes.draw do
  root 'violations#analyze'
  delete '/reset_data' => 'violations#reset_data'

  resources :violations do
        collection { post :import}
  end

end

app/models/violation.rb
class Violation < ActiveRecord::Base
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Violation.create!(row.to_hash)
    end
  end

  def self.unique_categories
    Violation.uniq.pluck(:violation_category).sort{|a,b| a <=> b}
  end

  def self.category_count(category)
    Violation.where("violation_category = ?",category).count
  end

  def self.violations_in_category(category)
    violations_in_category = Violation.where("violation_category = ?",category)
    violations_in_category.sort { |a,b| a.violation_date <=> b.violation_date }
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController
  before_action :set_violation, only: [:show, :edit, :update, :destroy]

  def import
   Violation.import(params[:file])
   @violations = Violation.all
   @categories = Violation.unique_categories
   render 'analyze', notice: "New data imported."
  end

  def reset_data
    puts "access controller action - reset data"
    Violation.delete_all
    redirect_to root_path
  end

  # GET /violations
  # GET /violations.json
  def index
    @violations = Violation.all.sort { |a,b| a.violation_date <=> b.violation_date }
  end

  # GET /violations/1
  # GET /violations/1.json

  def analyze
      @categories = Violation.unique_categories
  end

  def show
  end

  # GET /violations/new
  def new
    @violation = Violation.new
  end

  # GET /violations/1/edit
  def edit
  end

  # POST /violations
  # POST /violations.json
  def create
    @violation = Violation.new(violation_params)

    respond_to do |format|
      if @violation.save
        format.html { redirect_to @violation, notice: 'Violation was successfully created.' }
        format.json { render :show, status: :created, location: @violation }
      else
        format.html { render :new }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /violations/1
  # PATCH/PUT /violations/1.json
  def update
    respond_to do |format|
      if @violation.update(violation_params)
        format.html { redirect_to @violation, notice: 'Violation was successfully updated.' }
        format.json { render :show, status: :ok, location: @violation }
      else
        format.html { render :edit }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /violations/1
  # DELETE /violations/1.json
  def destroy
    @violation.destroy
    respond_to do |format|
      format.html { redirect_to violations_url, notice: 'Violation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_violation
      @violation = Violation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def violation_params
      params.require(:violation).permit(:violation_id, :inspection_id, :violation_category, :violation_date, :violation_date_closed, :violation_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/violations_helper.rb
module ViolationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeforamericaChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/violations/_form.html.erb
<%= form_for(@violation) do |f| %>
  <% if @violation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@violation.errors.count, "error") %> prohibited this violation from being saved:</h2>

      <ul>
      <% @violation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :violation_id %><br>
    <%= f.number_field :violation_id %>
  </div>
  <div class="field">
    <%= f.label :inspection_id %><br>
    <%= f.number_field :inspection_id %>
  </div>
  <div class="field">
    <%= f.label :violation_category %><br>
    <%= f.text_field :violation_category %>
  </div>
  <div class="field">
    <%= f.label :violation_date %><br>
    <%= f.text_field :violation_date %>
  </div>
  <div class="field">
    <%= f.label :violation_date_closed %><br>
    <%= f.text_field :violation_date_closed %>
  </div>
  <div class="field">
    <%= f.label :violation_type %><br>
    <%= f.text_field :violation_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/violations/analyze.html.erb
<p id="notice"><%= notice %></p>

<% if Violation.count == 0 %>

  <h1>Import Violations </h1>
  <p>
    To import data, first download the file found at: <a href="http://forever.codeforamerica.org/fellowship-2015-tech-interview/Violations-2012.csv">
    http://forever.codeforamerica.org/fellowship-2015-tech-interview/Violations-2012.csv
    </a>
  </p>
  <p>
    Then attach that file below, and click "Import CSV"
  </p>
  <%= form_tag import_violations_path,  multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV", class: 'btn btn-success' %>
  <% end %>

  <% else %>

<%= button_to "Reset data", reset_data_path, method: :delete, class: 'btn btn-danger' %>
<br>
<%= link_to "View all violations", violations_path, class: 'btn btn-primary' %>

<% end %>



<h1>Violations Analysis</h1>

<% if @categories.count == 0 %>

<h3 class="alert alert-warning">
  Please import data first.
</h3>

<% else %>

<table class="violations-table">
  <thead>
    <tr>
      <th>Violation category</th>
      <th>Count of Violations</th>
      <th>Earliest Violation</th>
      <th>Latest Violation</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category %></td>
        <td><%=  Violation.category_count(category) %></td>
        <td><%=  Violation.violations_in_category(category).first.violation_date.strftime("%m/%d/%Y") %></td>
        <td><%=  Violation.violations_in_category(category).last.violation_date.strftime("%m/%d/%Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/violations/edit.html.erb
<h1>Editing Violation</h1>

<%= render 'form' %>

<%= link_to 'Show', @violation %> |
<%= link_to 'Back', violations_path %>

app/views/violations/index.html.erb
<p id="notice"><%= notice %></p>

<% if Violation.count == 0 %>

<h1>Import Violations CSV </h1>
<%= form_tag import_violations_path,  multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <br>
  <%= submit_tag "Import CSV", class: 'btn btn-primary' %>
<% end %>

<% end %>

<%= link_to "Analyze Violations", root_path, class: 'btn btn-success' %>

<h1>All Violations - sorted by violation date</h1>

<table class="violations-table">
  <thead>
    <tr>
      <th>Violation</th>
      <th>Inspection</th>
      <th>Violation category</th>
      <th>Violation date</th>
      <th>Violation date closed</th>
      <th>Violation type</th>
    </tr>
  </thead>

  <tbody>
    <% @violations.each do |violation| %>
      <tr>
        <td><%= violation.violation_id %></td>
        <td><%= violation.inspection_id %></td>
        <td><%= violation.violation_category %></td>
        <td><%= violation.violation_date %></td>
        <td><%= violation.violation_date_closed %></td>
        <td><%= violation.violation_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Violation', new_violation_path %>

app/views/violations/new.html.erb
<h1>New Violation</h1>

<%= render 'form' %>

<%= link_to 'Back', violations_path %>

app/views/violations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Violation:</strong>
  <%= @violation.violation_id %>
</p>

<p>
  <strong>Inspection:</strong>
  <%= @violation.inspection_id %>
</p>

<p>
  <strong>Violation category:</strong>
  <%= @violation.violation_category %>
</p>

<p>
  <strong>Violation date:</strong>
  <%= @violation.violation_date %>
</p>

<p>
  <strong>Violation date closed:</strong>
  <%= @violation.violation_date_closed %>
</p>

<p>
  <strong>Violation type:</strong>
  <%= @violation.violation_type %>
</p>

<%= link_to 'Edit', edit_violation_path(@violation) %> |
<%= link_to 'Back', violations_path %>